COZE_API_KEY = "pat_DnIQLPnuNKDINujgejoH7toje7fcM5DiMZ5SQh3yF6kBNfhiFAtgcC4Xmfpxrhad"
COZE_BOT_ID = "7474973051504050176" 

COZE_API_KEY1 = "pat_cTHawA4AwRQyevuVEr0owKCz6Dxu8BQsRu2BBIhFkd2H0THXFXaJaAmWcXFgjjlR"
COZE_BOT_ID1 = "7471918474705747977" 

DataBaseHOST = "http://107.175.54.30:8080"