COZE_API_KEY = "pat_yXOp5Ly2OuTJ9HimoLOsvUs6ZlsXrjU2DMLNnYN6wJR0iIinnU7DKcdQBD9vHREH"
COZE_BOT_ID = "7474973051504050176" 

COZE_API_KEY1 = "pat_3xeECicYAnAijwCVUaeMuZEvN4WLimnAfrmu9HApdw5amSPRsu142pqi49RLUVZV"
COZE_BOT_ID1 = "7471918474705747977" 