COZE_API_KEY = "pat_dmC9FkkXvjEkPKxYbeSO6l10MdJCVRs8p4JqHhfXguwyWxkr1PVJkoqvrYV5RH8b"
COZE_BOT_ID = "7474973051504050176" 

COZE_API_KEY1 = "pat_3xeECicYAnAijwCVUaeMuZEvN4WLimnAfrmu9HApdw5amSPRsu142pqi49RLUVZV"
COZE_BOT_ID1 = "7471918474705747977" 